all:

windows:
	g++ -I src/include -I src/classes -I src/jsoncpp/include -L src/lib -o main main.cpp src/jsoncpp/dist/jsoncpp.cpp -lmingw32 -lSDL2main -lSDL2

macOS:
	clang++ -I /Library/Frameworks/SDL2.framework/Versions/A/Headers -I src/classes -I src/jsoncpp/include -L src/lib -o main main.cpp src/jsoncpp/dist/jsoncpp.cpp -SDL2

clean:
	rm -f main