all:

windows:
	g++ -I src/include -L src/lib -o main main.cpp -lmingw32 -lSDL2main -lSDL2

macOS:
	clang++ -I /Library/Frameworks/SDL2.framework/Versions/A/Headers -L src/lib -o main main.cpp -SDL2

clean:
	rm -f main